export enum ChatV2ChannelType {
  MODEL_MATCHING = 'modelMatching',
  HAIR_CONSULTATION = 'hairConsultation',
  REVIEW_SPECIAL = 'reviewSpecial',
  JOB_POSTING = 'jobPosting',
}

export enum ChatV2PostType {
  MODEL_ANNOUNCEMENT = 'MODEL_ANNOUNCEMENT',
  QUICK_MATCHING_PREMIUM = 'QUICK_MATCHING_PREMIUM',
  QUICK_MATCHING_GENERAL = 'QUICK_MATCHING_GENERAL',
  EXPERIENCE_GROUP = 'EXPERIENCE_GROUP',
  CHAT = 'CHAT',
  HAIR_CONSULTATION = 'HAIR_CONSULTATION',
  REVIEW_SPECIAL = 'REVIEW_SPECIAL',
  JOB_POSTING = 'JOB_POSTING',
  RESUME = 'RESUME',
}

/**
 * Shared wire contract with Flutter and the job WebView client.
 * Update all three definitions and their contract tests together.
 */
export enum ChatOriginEntrySource {
  MODEL_ANNOUNCEMENT_DETAIL_APPLY_CHAT = 'MODEL_ANNOUNCEMENT_DETAIL_APPLY_CHAT',
  QUICK_MATCHING_GENERAL_DETAIL_CHAT = 'QUICK_MATCHING_GENERAL_DETAIL_CHAT',
  QUICK_MATCHING_PREMIUM_DETAIL_CHAT = 'QUICK_MATCHING_PREMIUM_DETAIL_CHAT',
  EXPERIENCE_GROUP_DETAIL_CHAT = 'EXPERIENCE_GROUP_DETAIL_CHAT',
  HAIR_CONSULTATION_POST_COMMENT_DIRECT_CHAT = 'HAIR_CONSULTATION_POST_COMMENT_DIRECT_CHAT',
  HAIR_CONSULTATION_POST_COMMENT_DESIGNER_PROFILE_MENU_INQUIRY = 'HAIR_CONSULTATION_POST_COMMENT_DESIGNER_PROFILE_MENU_INQUIRY',
  HAIR_CONSULTATION_RESPONSE_DETAIL_DIRECT_CHAT = 'HAIR_CONSULTATION_RESPONSE_DETAIL_DIRECT_CHAT',
  HAIR_CONSULTATION_RESPONSE_DETAIL_DESIGNER_PROFILE_MENU_INQUIRY = 'HAIR_CONSULTATION_RESPONSE_DETAIL_DESIGNER_PROFILE_MENU_INQUIRY',
  REVIEW_SPECIAL_RESERVATION_ACCEPT_CHAT = 'REVIEW_SPECIAL_RESERVATION_ACCEPT_CHAT',
  JOB_POSTING_DETAIL_APPLY_CHAT = 'JOB_POSTING_DETAIL_APPLY_CHAT',
  RESUME_DETAIL_OFFER_CHAT = 'RESUME_DETAIL_OFFER_CHAT',
  MODEL_PROFILE_DIRECT_CHAT = 'MODEL_PROFILE_DIRECT_CHAT',
  DESIGNER_PROFILE_MENU_INQUIRY = 'DESIGNER_PROFILE_MENU_INQUIRY',
  QUICK_MATCHING_GENERAL_DESIGNER_PROFILE_MENU_INQUIRY = 'QUICK_MATCHING_GENERAL_DESIGNER_PROFILE_MENU_INQUIRY',
  QUICK_MATCHING_PREMIUM_DESIGNER_PROFILE_MENU_INQUIRY = 'QUICK_MATCHING_PREMIUM_DESIGNER_PROFILE_MENU_INQUIRY',
  RECENT_ACCESS_RECOMMENDED_MODEL_PROFILE_CHAT = 'RECENT_ACCESS_RECOMMENDED_MODEL_PROFILE_CHAT',
  NEW_MODEL_PROFILE_CHAT = 'NEW_MODEL_PROFILE_CHAT',
  RECENT_FEMALE_MODEL_PROFILE_CHAT = 'RECENT_FEMALE_MODEL_PROFILE_CHAT',
  RECENT_MALE_MODEL_PROFILE_CHAT = 'RECENT_MALE_MODEL_PROFILE_CHAT',
  NEARBY_MODEL_PROFILE_CHAT = 'NEARBY_MODEL_PROFILE_CHAT',
  BEAUTY_MODEL_PROFILE_CHAT = 'BEAUTY_MODEL_PROFILE_CHAT',
  ACTIVE_MODEL_PROFILE_CHAT = 'ACTIVE_MODEL_PROFILE_CHAT',
  FAVORITE_MODEL_PROFILE_CHAT = 'FAVORITE_MODEL_PROFILE_CHAT',
  QUICK_MATCHING_GENERAL_MODEL_PROFILE_CHAT = 'QUICK_MATCHING_GENERAL_MODEL_PROFILE_CHAT',
  QUICK_MATCHING_PREMIUM_MODEL_PROFILE_CHAT = 'QUICK_MATCHING_PREMIUM_MODEL_PROFILE_CHAT',
  TOP_ADVISOR_DESIGNER_PROFILE_MENU_INQUIRY = 'TOP_ADVISOR_DESIGNER_PROFILE_MENU_INQUIRY',
  RECOMMENDER_DESIGNER_PROFILE_MENU_INQUIRY = 'RECOMMENDER_DESIGNER_PROFILE_MENU_INQUIRY',
  NO_FACE_SHOOTING_DESIGNER_PROFILE_MENU_INQUIRY = 'NO_FACE_SHOOTING_DESIGNER_PROFILE_MENU_INQUIRY',
  SEARCH_MAP_DESIGNER_PROFILE_MENU_INQUIRY = 'SEARCH_MAP_DESIGNER_PROFILE_MENU_INQUIRY',
  FAVORITE_NOTIFICATION_MODEL_PROFILE_CHAT = 'FAVORITE_NOTIFICATION_MODEL_PROFILE_CHAT',
  HAIR_CONSULTATION_ANSWER_NOTIFICATION_MODEL_PROFILE_CHAT = 'HAIR_CONSULTATION_ANSWER_NOTIFICATION_MODEL_PROFILE_CHAT',
  STORELINK_NOTIFICATION_MODEL_PROFILE_CHAT = 'STORELINK_NOTIFICATION_MODEL_PROFILE_CHAT',
  INSTAGRAM_NOTIFICATION_MODEL_PROFILE_CHAT = 'INSTAGRAM_NOTIFICATION_MODEL_PROFILE_CHAT',
}

/**
 * Shared nullable pricing contract with Flutter and the job WebView client.
 * Update all three definitions and contract tests together.
 */
export enum ChatOriginPricingType {
  PAY = 'pay',
  NEW = 'new',
  RECENT_MALE = 'recent_male',
  RECENT_FEMALE = 'recent_female',
  LONG_TIME = 'longTime',
  BEAUTY = 'beauty',
  FAVORITE = 'favorite',
  THUNDER_DEFAULT = 'thunder_default',
  FAVORITE_NOTIFICATION_DESIGNER = 'favorite_notification_designer',
  VIEW_HAIR_CONSULTATION_ANSWER_NOTIFICATION_DESIGNER = 'view_hair_consultation_answer_notification_designer',
  VIEW_STORELINK_NOTIFICATION_DESIGNER = 'view_storelink_notification_designer',
  VIEW_INSTAGRAM_NOTIFICATION_DESIGNER = 'view_instagram_notification_designer',
}

export type ChatStartRequest = {
  channelType: ChatV2ChannelType;
  postType: ChatV2PostType;
  postId: string;
  targetUserId: string;
  originEntrySource: ChatOriginEntrySource;
  originPricingType?: ChatOriginPricingType | null;
  answerId?: string;
  joinType?: 'MODEL' | 'DESIGNER';
  isMyHairConsultationPost?: boolean;
  targetDisplayName?: string;
};

export type HairConsultationDirectChatOrigin =
  | ChatOriginEntrySource.HAIR_CONSULTATION_POST_COMMENT_DIRECT_CHAT
  | ChatOriginEntrySource.HAIR_CONSULTATION_RESPONSE_DETAIL_DIRECT_CHAT;

type HairConsultationChatStartRequestInput = {
  postId: string;
  answerId: string;
  targetUserId: string;
  originEntrySource: HairConsultationDirectChatOrigin;
  joinType: 'MODEL' | 'DESIGNER';
  isMyHairConsultationPost: boolean;
  targetDisplayName?: string;
};

/**
 * 헤어컨설팅의 직접 채팅 CTA가 Flutter v2 시작 경계에 전달할 요청을 만든다.
 *
 * 방 identity는 원문 글이 아니라 답변 단위이므로 `answerId`를 필수 입력으로
 * 유지한다. 프로필 경유 메뉴 문의는 modelMatching 공고 방을 사용하므로 이
 * 빌더의 범위가 아니다.
 */
export function buildHairConsultationChatStartRequest({
  postId,
  answerId,
  targetUserId,
  originEntrySource,
  joinType,
  isMyHairConsultationPost,
  targetDisplayName,
}: HairConsultationChatStartRequestInput): ChatStartRequest {
  return {
    channelType: ChatV2ChannelType.HAIR_CONSULTATION,
    postType: ChatV2PostType.HAIR_CONSULTATION,
    postId,
    answerId,
    targetUserId,
    originEntrySource,
    joinType,
    isMyHairConsultationPost,
    ...(targetDisplayName !== undefined && { targetDisplayName }),
  };
}
