export const CONSULTING_RESPONSE_SIDEBAR_TAB_VALUE = {
  PHOTOS: 'photos',
  TREATMENTS: 'treatments',
  PREFERRED_STYLE: 'preferredStyle',
  ETC: 'etc',
} as const;

export const CONSULTING_RESPONSE_SIDEBAR_TAB = {
  [CONSULTING_RESPONSE_SIDEBAR_TAB_VALUE.PHOTOS]: {
    label: '사진',
    value: CONSULTING_RESPONSE_SIDEBAR_TAB_VALUE.PHOTOS,
  },
  [CONSULTING_RESPONSE_SIDEBAR_TAB_VALUE.TREATMENTS]: {
    label: '시술이력',
    value: CONSULTING_RESPONSE_SIDEBAR_TAB_VALUE.TREATMENTS,
  },
  [CONSULTING_RESPONSE_SIDEBAR_TAB_VALUE.PREFERRED_STYLE]: {
    label: '선호스타일',
    value: CONSULTING_RESPONSE_SIDEBAR_TAB_VALUE.PREFERRED_STYLE,
  },
  [CONSULTING_RESPONSE_SIDEBAR_TAB_VALUE.ETC]: {
    label: '기타',
    value: CONSULTING_RESPONSE_SIDEBAR_TAB_VALUE.ETC,
  },
} as const;

export const CONSULTING_RESPONSE_SIDEBAR_TABS = Object.values(CONSULTING_RESPONSE_SIDEBAR_TAB);
