export const HAIR_CONSULTATION_FORM_FIELD_NAME = {
  HAIR_LENGTH: 'hairLength',
  HAIR_CONCERNS: 'hairConcerns',
  HAIR_TEXTURE: 'hairTexture',
  SKIN_BRIGHTNESS: 'skinBrightness',
  PERSONAL_COLOR: 'personalColor',
  TREATMENTS: 'treatments',
  TREATMENT_DETAIL: 'treatmentDetail',
  ASPIRATION_IMAGES: 'aspirationImages',
  PRICE: 'price',
  DESIRED_DATE_TYPE: 'desiredDateType',
  DESIRED_DATE: 'desiredDate',
  MY_IMAGES: 'myImages',
  TITLE: 'title',
  CONTENT: 'content',
} as const;
