export const MY_IMAGE_TYPE = {
  RECENT: 'RECENT',
  FRONT: 'FRONT',
  SIDE: 'SIDE',
  WHOLE_BODY: 'WHOLE_BODY',
} as const;

export const REQUIRED_MY_IMAGE_TYPES = [
  MY_IMAGE_TYPE.FRONT,
  MY_IMAGE_TYPE.SIDE,
  MY_IMAGE_TYPE.RECENT,
] as const;
