export const SKIN_TONE_OPTION_VALUE = {
  VERY_BRIGHT: 'veryBright',
  BRIGHT: 'bright',
  NORMAL: 'normal',
  DARK: 'dark',
  VERY_DARK: 'veryDark',
} as const;

export const SKIN_TONE_OPTION_LABEL = {
  [SKIN_TONE_OPTION_VALUE.VERY_BRIGHT]: '매우 밝음',
  [SKIN_TONE_OPTION_VALUE.BRIGHT]: '밝음',
  [SKIN_TONE_OPTION_VALUE.NORMAL]: '보통',
  [SKIN_TONE_OPTION_VALUE.DARK]: '어두움',
  [SKIN_TONE_OPTION_VALUE.VERY_DARK]: '매우 어두움',
} as const;

export const SKIN_TONE_OPTION = {
  [SKIN_TONE_OPTION_VALUE.VERY_BRIGHT]: {
    label: SKIN_TONE_OPTION_LABEL[SKIN_TONE_OPTION_VALUE.VERY_BRIGHT],
    value: SKIN_TONE_OPTION_VALUE.VERY_BRIGHT,
    color: '#FFFCFB',
  },
  [SKIN_TONE_OPTION_VALUE.BRIGHT]: {
    label: SKIN_TONE_OPTION_LABEL[SKIN_TONE_OPTION_VALUE.BRIGHT],
    value: SKIN_TONE_OPTION_VALUE.BRIGHT,
    color: '#FFF6F1',
  },
  [SKIN_TONE_OPTION_VALUE.NORMAL]: {
    label: SKIN_TONE_OPTION_LABEL[SKIN_TONE_OPTION_VALUE.NORMAL],
    value: SKIN_TONE_OPTION_VALUE.NORMAL,
    color: '#FDF0E9',
  },
  [SKIN_TONE_OPTION_VALUE.DARK]: {
    label: SKIN_TONE_OPTION_LABEL[SKIN_TONE_OPTION_VALUE.DARK],
    value: SKIN_TONE_OPTION_VALUE.DARK,
    color: '#EFDDD4',
  },
  [SKIN_TONE_OPTION_VALUE.VERY_DARK]: {
    label: SKIN_TONE_OPTION_LABEL[SKIN_TONE_OPTION_VALUE.VERY_DARK],
    value: SKIN_TONE_OPTION_VALUE.VERY_DARK,
    color: '#EAD3C8',
  },
} as const;
