export type KnownMongConsumePresetType =
  | 'CHAT'
  | 'THUNDER_ANNOUNCEMENTS'
  | 'HAIR_CONSULTING'
  | 'INSTAGRAM'
  | 'RESERVATIONS'
  | 'EXPERIENCE_GROUPS';

export type MongConsumePresetType = KnownMongConsumePresetType | (string & {});

export type KnownMongConsumePresetSubType =
  | 'RECOMMEND_MODEL_CHAT'
  | 'NEW_MODEL_CHAT'
  | 'MALE_MODEL_CHAT'
  | 'FEMALE_MODEL_CHAT'
  | 'NEARBY_MODEL_CHAT'
  | 'BEAUTY_MODEL_CHAT'
  | 'FAVORITE_MODEL_CHAT'
  | 'RECOMMENDER_DESIGNER_CHAT'
  | 'OPEN_RECEIVED_CHAT_DESIGNER'
  | 'FAVORITE_NOTIFICATION_CHAT_DESIGNER'
  | 'FAVORITE_NOTIFICATION_CHAT_MODEL'
  | 'VIEW_HAIR_CONSULTATION_ANSWER_NOTIFICATION_CHAT_DESIGNER'
  | 'VIEW_STORELINK_NOTIFICATION_CHAT_DESIGNER'
  | 'VIEW_INSTAGRAM_NOTIFICATION_CHAT_DESIGNER'
  | 'MY_HAIR_CONSULTATIONS_ANSWER_CHAT_MODEL'
  | 'MY_HAIR_CONSULTATIONS_COMMENT_CHAT_MODEL'
  | 'OTHER_HAIR_CONSULTATIONS_ANSWER_CHAT_MODEL'
  | 'OTHER_HAIR_CONSULTATIONS_COMMENT_CHAT_MODEL'
  | 'THUNDER_ANNOUNCEMENTS_DEFAULT_CHAT_MODEL'
  | 'THUNDER_ANNOUNCEMENTS_DEFAULT_CHAT_DESIGNER'
  | 'HAIR_CONSULTATIONS_TOP_ADVISORS_CHAT_MODEL'
  | 'THUNDER_ANNOUNCEMENTS_DEFAULT_DESIGNER'
  | 'THUNDER_ANNOUNCEMENTS_DEFAULT_MODEL'
  | 'THUNDER_ANNOUNCEMENTS_PREMIUM_DESIGNER'
  | 'THUNDER_ANNOUNCEMENTS_PREMIUM_MODEL'
  | 'CLICK_INSTAGRAM_MODEL'
  | 'VIEW_MY_HAIR_CONSULTATIONS_ANSWERS_MODEL'
  | 'HAIR_CONSULTATIONS_COMMENTS_DESIGNER'
  | 'RESERVATIONS_DESIGNER'
  | 'EXPERIENCE_GROUPS_LINK_DESIGNER';

export type MongConsumePresetSubType = KnownMongConsumePresetSubType | (string & {});

export type MongConsumePreset = {
  id: number;
  title: string;
  type: MongConsumePresetType;
  subType: MongConsumePresetSubType | '';
  price: number;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
};
