import type { MongConsumePresetSubType } from '@/entities/mong/api/mong-consume-preset';

export const MEEMONG_PASS_CREATE_TYPES = {
  THUNDER_ANNOUNCEMENTS_DEFAULT_CHAT_MODEL: 'THUNDER_ANNOUNCEMENTS_DEFAULT_CHAT_MODEL',
  HAIR_CONSULTATIONS_TOP_ADVISORS_CHAT_MODEL: 'HAIR_CONSULTATIONS_TOP_ADVISORS_CHAT_MODEL',
  MY_HAIR_CONSULTATIONS_ANSWER_CHAT_MODEL: 'MY_HAIR_CONSULTATIONS_ANSWER_CHAT_MODEL',
  MY_HAIR_CONSULTATIONS_COMMENT_CHAT_MODEL: 'MY_HAIR_CONSULTATIONS_COMMENT_CHAT_MODEL',
  OTHER_HAIR_CONSULTATIONS_ANSWER_CHAT_MODEL: 'OTHER_HAIR_CONSULTATIONS_ANSWER_CHAT_MODEL',
  OTHER_HAIR_CONSULTATIONS_COMMENT_CHAT_MODEL: 'OTHER_HAIR_CONSULTATIONS_COMMENT_CHAT_MODEL',
  CLICK_INSTAGRAM_MODEL: 'CLICK_INSTAGRAM_MODEL',
  VIEW_MY_HAIR_CONSULTATIONS_ANSWERS_MODEL: 'VIEW_MY_HAIR_CONSULTATIONS_ANSWERS_MODEL',
} as const;

type MeemongPassCreateType =
  (typeof MEEMONG_PASS_CREATE_TYPES)[keyof typeof MEEMONG_PASS_CREATE_TYPES];

const MEEMONG_PASS_FREE_MONG_CREATE_TYPES = new Set<MeemongPassCreateType>(
  Object.values(MEEMONG_PASS_CREATE_TYPES),
);

export function canSkipMongWithMeemongPass({
  isMeemongPassActive,
  createType,
}: {
  isMeemongPassActive: boolean;
  createType: MongConsumePresetSubType | string;
}) {
  return (
    isMeemongPassActive &&
    MEEMONG_PASS_FREE_MONG_CREATE_TYPES.has(createType as MeemongPassCreateType)
  );
}
